### ISSUE TITLE
Error on deploy

### ISSUE THREAD

**Issue by ramiel** [jzimmek/serverless-plugin-node-shim#1]
When deploying I get this error

```bash
Serverless: Applying node-shim...

[.....]/node_modules/serverless-plugin-node-shim/index.js:89
                    this.serverless.service.custom.nodeShim.execPath
                                                   ^

TypeError: Cannot read property 'nodeShim' of undefined
```
this happens if I run `sls deploy`

**Comment by ramiel** [comment]
Sorry, I forgot to include this in the serverless configuration

```yaml
custom:
  nodeShim:
    execPath: node-v8.9.4-linux-x64/bin/node
```
